# Generated by Django 5.2.8 on 2025-12-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('xisobchi', 'Xisobchi'), ('qorovul', 'Qorovul'), ('omborchi', 'Omborchi'), ('kafedra', 'Kafedra'), ('usta', 'Usta'), ('fakultet', 'Fakultet')], default='admin', max_length=18),
        ),
    ]
