# Generated by Django 5.2.8 on 2025-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='remont_bolimi',
            name='status',
            field=models.CharField(choices=[('YANGI', 'Yangi'), ('BIRIKTIRILGAN', 'Biriktirilgan'), ('REMONT', 'Remont'), ('XISOBDAN CHIQARILGAN', 'Xisobdan Chiqarilgan'), ('CHIQQAN', 'Chiqqan'), ('QAYTGAN', 'Qaytgan')], default='CHIQQAN', max_length=128),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('YANGI', 'Yangi'), ('BIRIKTIRILGAN', 'Biriktirilgan'), ('REMONT', 'Remont'), ('XISOBDAN CHIQARILGAN', 'Xisobdan Chiqarilgan'), ('CHIQQAN', 'Chiqqan'), ('QAYTGAN', 'Qaytgan')], default='YANGI', max_length=20),
        ),
    ]
