# Generated by Django 5.2.8 on 2025-12-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remont_bolimi_status_alter_material_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remont_bolimi',
            old_name='status',
            new_name='status_new',
        ),
    ]
