# Generated by Django 5.2.8 on 2025-12-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_status_remont_bolimi_status_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='uzgarish_sababi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uzgarish_sababi', to='main.change_reason'),
        ),
    ]
