# Generated by Django 5.2.8 on 2025-12-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_material_uzgarish_sababi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='uzgarish_sababi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.change_reason'),
        ),
    ]
