# Generated by Django 5.2.8 on 2025-12-21 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_material_uzgarish_sababi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='foydalanuvchi_shaxs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foydalanuvchi_shaxs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='izoh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='javobgar_shaxs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='javobgar_shaxs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='joylashgan_bino',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='kafedra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kafedra'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mac_raqami',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='oxirgi_xolati',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='qabul_qilgan_javobgar_shaxs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qabul_qilgan_javobgar_shaxs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='royxatdan_chiqarish',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='uzgarish_sababi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.change_reason'),
        ),
        migrations.AlterField(
            model_name='material',
            name='xolati',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
