# Generated by Django 5.2.8 on 2025-12-25 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_material_foydalanuvchi_shaxs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('xisobchi', 'Xisobchi'), ('qorovul', 'Qorovul'), ('omborchi', 'Omborchi'), ('kafedra', 'Kafedra'), ('usta', 'Usta'), ('fakultet', 'Fakultet'), ('talaba', 'Talaba')], default='admin', max_length=18),
        ),
        migrations.CreateModel(
            name='Remont_Talab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xona', models.CharField(max_length=50)),
                ('izoh', models.TextField()),
                ('status', models.CharField(choices=[('YANGI', 'Yangi'), ('BEKOR QILINGAN', 'Bekor Qilingan'), ('TASDIQLANGAN', 'Tasdiqlangan')], default='YANGI', max_length=20)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kafedra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
