# Generated by Django 5.2.8 on 2026-08-10 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customuser_role_remont_talab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remont_bolimi',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='remont_talab',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='remont_bolimi',
            name='status_new',
            field=models.CharField(choices=[('REMONT', 'Remont'), ('TAYYOR', 'Tayyor')], default='REMONT', max_length=128),
        ),
        migrations.CreateModel(
            name='MaterialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BIRIKTIRISH', 'Biriktirish (berish)'), ('QAYTARISH', 'Qaytarish'), ('REMONTGA_BERISH', 'Remontga berish'), ('REMONTDAN_QAYTISH', 'Remontdan qaytish'), ('XISOBDAN_CHIQARISH', 'Hisobdan chiqarish')], max_length=30)),
                ('xona', models.CharField(blank=True, max_length=50, null=True)),
                ('old_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=30, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_history_created', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_history_from', to=settings.AUTH_USER_MODEL)),
                ('kafedra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kafedra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.material')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_history_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material tarixi',
                'verbose_name_plural': 'Material tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
